### ISSUE TITLE
Teach Tool - Misc Items and Checklist

### ISSUE THREAD

**Issue by arjunk** [avniproject/lfeteach#5]
##Context
https://docs.google.com/spreadsheets/d/1lEQEJLy8msdZ8d203QMt3xxKxc2hoKqny--c0mvvDj8/edit#gid=1773815132

## Acceptance Criteria

- [x] 1. Form should have two Segments - Segment 1 and Segment 2, section for Average scores, capture the elements the observer wants to provide feedback on, Date of next observation
- [x] 2. Each Segment will have the following Basic Details, Timed Questions and Pages for 9 Elements
- [x] 3. Basic details page should cover: Grade, Subject, Class size, Scheduled Time, Actual Time
- [x] 4. Grade-  Single Select based on the grades in the school. Give options for 1-9
- [x] 5.  Subject - Single Select with following options
 - English
 - Math
 - Science
- Social Studies
 - Other
- [x] 6. Class Size- Number entry - two fields for Girls & Boys
- [x] 7.  Scheduled Time & Actual Time: Clock / Time field
- [x] 8. Users should have Track location on
- [x] 9. Colour for each page title should be same as shown in the Teach Tool
- [x] 10. Questions should hide / show based on whether it is a primary tool (Grades 1-5) or secondary tool (Grades 6-10)
- [x] 11. The score fields on each element should read like "Overall Supportive Learning Enviornment Score "
- [x] 12. After the two segments, there should be a page "Average scores and Feedback" for showing Average scores across two segments. The last question on this page should be Feedback which has Multi-select answers for each element
- [x] 13. Last page should have a question "Next observation date"
- [x] 14. The next form should get scheduled based on this date
- [x] 15. Score field should hide the non applicable options based on following logic
  - If all Behaviours are scored L and then hide 3,  4 or 5
  - If all Behaviours are scored H then hide  1, 2 or 3 .
