### ISSUE TITLE
LFE Teach Observations Aug2023

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/lfeteach#55]
LFE wants to do next round of Observations with Teachers. They are aiming to do it in August so naming this round of Observation as "Aug2023".  
They want to do it after doing some changes in the application. below is the attached list of action items to be done before moving to production as per client feedback during UAT.

https://docs.google.com/spreadsheets/d/13H2UO1TqZdOvXzazGVF65cxlI7SCd2SYVBJFUVGOqUI/edit#gid=0

Also, they have to update the Observers and Teachers database. There are observers whose mobile numbers have changed, teacher transfers, new teachers are added, may be some teachers retired, etc. 
Thus there will be changes in users, locations, catchments, subjects and so on. There will be CSVs uploads related to this.

**Comment by salilsamanvay** [comment]
Client is facing some issue checked on 17th July 2023: 

- [ ] question 0.3 is reflecting for primary at the time when observer starts filling the response, it should behave same as the reminder is displayed currently. 
- [ ] Score options (1 - 5) are not getting changed basis response (H/ M/ L) of questions in the section. it was changing previously. please check the logic and implement the same.
- [ ] for timer right now 14 min 20 sec logic is implemented (4 min + 20 sec reminder+ 4 min 40 sec + 20 sec reminder + 4 min 40 sec + 20 sec reminder), we just need to add 40 sec more in the last to make a segment total duration of 15 mins as it teach tool time guideline, and after 15 mins only question should be displayed for answer to the observer. no edit for reminder positioning, for the last 40 sec only timer will be displayed.
- [ ] Client is facing slow response while selecting the option for answers, she wanted us to check if app is slow or her mobile is having some issue. currently she is facing at times 5 sec of delay in touching the screen and option getting selected. 
- [ ] option to explore: time selection method for observation start time is in 24 hours right now, do we have capability to make it 12 hour and then ask for AM / PM
